# Generated by Django 4.2.5 on 2023-09-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='birthday_day',
            new_name='birthday',
        ),
    ]
