# Generated by Django 4.2.5 on 2023-09-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='human',
            table='clinic_human',
        ),
    ]
